essentialkaos/ek

- changelog.md
- log/log.go
- log/log_test.go
* [`log`] Fixed bug with logging empty strings
> Version 1.8.2

- changelog.md
- req/req.go
- req/req_test.go
* `[req]` `RequestTimeout` set to 0 (_disabled_) by default
> Version 3.1.3

- changelog.md
- fsutil/fs.go
- fsutil/fs_windows.go
- readme.md
- strutil/strutil.go
- strutil/strutil_test.go
* `[strutil]` Added method `Len` which return number of symbols in string
* `[strutil]` UTF-8 support for `Substr`, `Tail`, `Head` and `Elipsis` methods
* `[strutil]` Added some benchmarks to tests
* `[fsutil]` Fixed `GetPerm` stub for Windows
* `[fsutil]` Fixed package description
> Version 3.2.0

- changelog.md
- strutil/strutil.go
* `[strutil]` Fixed bug with overflowing int in `Tail` method
> Version 3.4.2

- .travis.yml
- Makefile
- changelog.md
- fmtc/fmtc.go
- fmtc/fmtc_test.go
- readme.md
- terminal/terminal.go
- tmp/tmp.go
- tmp/tmp_test.go
- usage/usage.go
* `[terminal]` Added hints support from new version of `go-linenoise` :fire: 
* `[fmtc]` Light colors tag (`-`) support :fire:
* `[terminal]` Using forked [go.linenoise](https://github.com/essentialkaos/go-linenoise) package instead original
* `[fmtc]` Changed colors for `{s}` and `{S}` tags from light grey to dark grey
* `[usage]` Using dark grey color for option values and example description
* `[tmp]` Added `DefaultDirPerms` and `DefaultFilePerms` global variables for permissions customization
> Version 3.5.0

- changelog.md
- fmtutil/separator.go
- usage/usage.go
* `[usage]` Using dark grey color for license and copyright
* `[fmtutil]` Added global variable `SeparatorColorTag` for separator color customization
* `[fmtutil]` Added global variable `SeparatorTitleColorTag` for separator title color customization
> Version 3.5.1

- changelog.md
- fmtutil/fmtutil.go
- fmtutil/fmtutil_test.go
- usage/usage.go
* `[usage]` Added breadcrumbs output for commands and options
* `[usage]` Changed color for arguments from dark grey to light grey
* `[fmtutil]` Fixed special symbols colorization in `ColorizePassword`
> Version 5.4.0

- changelog.md
- knf/knf.go
- knf/knf_test.go
* `[knf]` Return default value for the property even if config struct is nil
> Version 7.2.0

- changelog.md
- version/version.go
- version/version_test.go
* `[version]` Added method `Int()` which return version as integer
* `[version]` Fixed bug with version comparison (#114)
> Version 0.9.1

- changelog.md
- fmtutil/table/table.go
* `[fmtutil/table]` Fixed bug with color tags in headers when colors is disabled
> Version 9.1.4

- changelog.md
- fmtc/fmtc.go
- knf/knf.go
- knf/knf_test.go
* `[fmtc]` Added method `NewT` which creates a new struct for working with the temporary output
* `[fmtc]` More docs about color tags
* `[knf]` Removing trailing spaces from property values
> Version 9.7.0

- changelog.md
- fmtc/examples_test.go
- fmtc/fmtc.go
- fmtc/fmtc_test.go
* `[fmtc]` Improved utf8 support in temporary messages
> Version 9.7.1

- changelog.md
- req/req.go
- strutil/example_test.go
- strutil/strutil.go
- strutil/strutil_test.go
- system/info.go
- system/info_cpu.go
- system/info_fs.go
- system/info_loadavg.go
- system/info_memory.go
- system/info_net.go
- system/info_test.go
- system/info_uptime.go
- system/process/process.go
- system/process/process_cpu.go
- system/process/process_memory.go
- system/user.go
- system/user_unix.go
* `[strutil]` Added ellipsis suffix customization
* `[strutil]` Added support of custom separators for `ReadField`
* `[system]` Improved `id` and `getent` commands output parsing
* `[req]` Closing response body after parsing data
* `[system]` Fixed bug with parsing `id` command output with empty group names (#148)
* `[system]` Fixed bug with calculating transferred bytes on active interfaces
> Version 9.15.0

- options/options.go
- options/options_test.go
Patch which fixed a bug that occurs with usage `Bound` and `Conflict` flags in command line with no arguments and options.
I have added one extra check in `validate()` function. In case we do not have bounded or conflicted arguments in our options map, we should not append an error to error list.
1. Declare options map with two options.
2. Link one of them to another by `Bound` of `Conflict` field.
3. Execute program with no arguments.
```
[...]
var optMap = options.Map{
OPT_SIZELIMIT: {Type: options.STRING, Bound: OPT_KEEPFILES},
OPT_KEEPFILES: {Type: options.INT, Value: 0},
}
opts, errs := options.Parse(optMap)
if len(errs) != 0 {
for _, err := range errs {
fmt.Println(err.Error())
}
}
```
I expect that program will be successfully finished with no errors, but it does not.
**Is this …
> Fix EK options checks with bound and conflict fields

- changelog.md
- ek.go
* Dependencies now download with initial `go get` command
> Version 9.17.4

- .codebeatsettings
- .travis.yml
- changelog.md
- fmtc/examples_test.go
- fmtc/fmtc.go
- fmtc/fmtc_test.go
* `[fmtc]` Temporary output feature moved from T struct to `TPrintf` and `TPrintln`
**NOTE:** Due to various degradation of TravisCI OSX infrastructure, the build fails on OSX is allowed for now.
> Version 9.18.0

- changelog.md
- system/user_unix.go
* `[system]` Fixed bug with extra new line symbol in user `Shell` field
> Version 9.18.1

- CHANGELOG.md
- fmtc/fmtc.go
- fmtc/fmtc_test.go
- fmtc/fuzz.go
* `[fmtc]` Added fuzz testing
* `[fmtc]` Fixed bug with parsing `{}` and `{-}` as valid color tags
> Version 9.26.2

- .travis.yml
- .travis/windows.sh
- CHANGELOG.md
- system/info.go
- system/info_cpu_linux.go
- system/info_net_linux.go
- system/info_test.go
- system/info_windows.go
* `[fmtutil/table]` Added global variable `MaxWidth` for configuration of maximum table width
* `[system]` Added method `GetCPUInfo` for fetching info about CPUs from procfs
* `[system]` `FSInfo` now is `FSUsage` (_incompatible changes_)
* `[system]` `MemInfo` now is `MemUsage` (_incompatible changes_)
* `[system]` `CPUInfo` now is `CPUUsage` (_incompatible changes_)
* `[system]` `InterfaceInfo` now is `InterfaceStats` (_incompatible changes_)
* `[system]` `GetFSInfo()` now is `GetFSUsage()` (_incompatible changes_)
* `[system]` `GetMemInfo()` now is `GetMemUsage()` (_incompatible changes_)
* `[system]` `GetCPUInfo()` now is `GetCPUUsage()` (_incompatible changes_)
* `[system]` `GetInterfacesInfo()` now is `GetInterfacesStats()` (_incompatible changes_)
* `[initsystem]` `HasService()` now …
> Version 10.0.0

- CHANGELOG.md
- fmtc/fmtc.go
* `[fmtc]` Improved work with temporary output (`TPrintf`, `TPrintln`)
> Version 10.4.0

- CHANGELOG.md
- terminal/terminal.go
- `[terminal]` Fixed bug with output messages from `Error` and `Warn` to stdout instead of stderr (_introduced in_ `12.117.0` — 4c2bcacc2e335ab4e33187eaf3e969d7c08f7551)
> Version 12.123.2
