- .travis.yml
- changelog.md
- fmtutil/fmtutil_test.go
- fmtutil/termsize_linux_test.go
- system/user.go
- system/user_darwin.go
- system/user_linux.go
* `[system]` Fixed major bug with OS X compatibility
* `[fmtutil]` Fixed tests for OS X
> Version 1.3

- changelog.md
- strutil/strutil.go
- strutil/strutil_test.go
* `[strutil]` Added method Head for subtraction first symbols from the string
* `[strutil]` Added method Tail for subtraction last symbols from the string
> Version 1.3.1

- changelog.md
* `[strutil]` Added method Head for subtraction first symbols from the string
* `[strutil]` Added method Tail for subtraction last symbols from the string
> Version 1.3.2

- changelog.md
- strutil/strutil.go
- strutil/strutil_test.go
* `[strutil]` Fixed bug in Tail method
> Version 1.3.3

- .travis.yml
- changelog.md
- fsutil/fs_time_darwin.go
- fsutil/fs_time_freebsd.go
- fsutil/fs_windows.go
- log/log_test.go
- system/info.go
- system/info_linux.go
- system/info_posix.go
- system/user_darwin.go
- system/user_freebsd.go
- system/user_windows.go
* `[fsutil]` Added partial FreeBSD support
* `[system]` Added partial FreeBSD support
* `[log]` Some minor fixes in tests
> Version 1.4.1

- .travis/script.sh
- changelog.md
- fsutil/fs.go
- fsutil/fs_test.go
* `[fsutil]` Added method `ProperPath` which return first proper path from given slice
> Version 1.4.2

- changelog.md
- errutil/errutil.go
- errutil/errutil_test.go
* `[errutil]` Improved Add method
> Version 1.4.3

- changelog.md
- errutil/errutil.go
- errutil/errutil_test.go
* `[errutil]` Added method Num which returns number of errors
> Version 1.4.4

- .travis.yml
- changelog.md
- pid/pid.go
* `[pid]` Fixed bug with pid file creation
* `[pid]` Increased coverage
> Version 1.4.5

- changelog.md
- tmp/tmp.go
- tmp/tmp_test.go
* `[tmp]` Improved error handling
* `[tmp]` Changed name pattern of temporary files and directories
> Version 1.5.0

- changelog.md
- knf/knf.go
- knf/knf_test.go
* `[knf]` Fixed bug in HasProp method which return true for unset properties
> Version 1.5.1

- changelog.md
- path/path.go
- path/path_test.go
- path/path_windows.go
- readme.md
* `[path]` Added package for working with paths
> Version 1.6.0

- changelog.md
- path/path_windows.go
* `[path]` 	Fixed windows stub
> Version 1.6.1

- changelog.md
- fsutil/fs.go
- fsutil/fs_time_darwin.go
- fsutil/fs_time_freebsd.go
- fsutil/fs_time_linux.go
- fsutil/fs_windows.go
* `[fsutil]` Added method ProperPath to windows stub
* `[fsutil]` Improved working with paths
> Versio 1.6.2

- changelog.md
- strutil/strutil.go
- strutil/strutil_test.go
* `[strutil]` Added methods PrefixSize and SuffixSize
> Version 1.6.3

- changelog.md
- path/path.go
- path/path_test.go
- path/path_windows.go
* `[path]` Added method IsDotfile for checking dotfile names
> Version 1.6.4

- changelog.md
- fsutil/file.go
- fsutil/fs.go
- fsutil/line_count.go
- fsutil/list.go
* `[fsutil]` Improved docs
* `[fsutil]` Added method (wrapper) for moving files
> Version 1.7.0

- changelog.md
- log/log.go
- log/log_test.go
* `[log]` Improved min level changing
> Version 1.7.1

- .travis.yml
- changelog.md
- errutil/errutil.go
- errutil/errutil_test.go
* `[errutil]` Added method Chain
> Version 1.7.2

- changelog.md
- fsutil/list.go
- fsutil/list_windows.go
- readme.md
* `[fsutil]` Method `ListAbsolute` ranamed to `ListToAbsolute`
* Improved readme
> Version 1.7.3

- fsutil/fs_test.go
- fsutil/list_windows.go
- fsutil/walker.go
- fsutil/walker_windows.go
* Added fs walker (bash `pushd`/`popd` analog)
> Version 1.7.4

- changelog.md
- env/env.go
- env/env_test.go
- env/env_windows.go
* [env] Added methods for getting env vars as string, int and float
* [env] Added tests
> Version 1.7.6

- .travis.yml
- env/env_test.go
- readme.md
* Updated list of projects with ek in readme
* Updated testing targets to latest versions of golang
> Updated list of projects with ek in readme

- changelog.md
- fsutil/fs_test.go
- fsutil/list.go
* [`fsutil`] Fixed bug in `List` function with filtering output
* [`fsutil`] Fixed bug with `NotPerms` filtering
> Version 1.7.7

- .travis.yml
- changelog.md
- terminal/terminal.go
* [`terminal`] Custom prompt support
* [`terminal`] Custom masking symbols support
* [`terminal`] Code refactoring
> Version 1.7.8

- changelog.md
- sortutil/sortutil.go
* [`sortutil`] Added method `VersionCompare` which can be used for custom version sorting
> Version 1.8.1

- changelog.md
- pid/pid.go
- pid/pid_darwin.go
- pid/pid_darwin_test.go
- pid/pid_linux.go
- pid/pid_linux_test.go
- pid/pid_test.go
- pid/pid_windows.go
* `[pid]` Added function `IsWorks` which return true if process with pid from pidfile is active
* `[pid]` Increased code coverage
> Version 2.0.2

- Makefile
- color/color.go
- color/color_test.go
- cron/cron.go
- kv/kv_test.go
- sortutil/sortutil.go
* Added makefile with some helpful commands (`fmt`, `deps`, `test`)
* Small fixes in docs
> Version 3.0.2

- changelog.md
- system/user.go
* `[system]` Removed debug output
> Version 3.0.3

- changelog.md
- req/req.go
* `[req]` Added `DialTimeout` and `RequestTimeout` variables for timeouts control
* `[req]` Lazy transport initialization
> Version 3.1.0

- changelog.md
- req/req.go
* `[req]` Small fixes in Request struct fields types
> Version 3.1.1

- changelog.md
- knf/knf_test.go
- strutil/strutil.go
* `[knf]` Fixed typo in tests
* `[strutil]` Removed unreachable code
> Version 3.2.1

- changelog.md
- req/req.go
* `[req]` Added content types constants
> Version 3.2.2

- changelog.md
- terminal/terminal.go
* `[terminal]` Fixed bug with title formating in `ReadUI` function
> Version 3.2.3

- changelog.md
- color/examples_test.go
- readme.md
- system/process/examples_test.go
- system/process/processes_linux.go
- system/process/processes_windows.go
- terminal/terminal.go
- tmp/examples_test.go
* `[system/process]` Added new package for getting information about active system processes
* `[terminal]` Fixed bug with title formating in `ReadAnswer` function
> Version 3.3.0

- changelog.md
- terminal/terminal_windows.go
- usage/usage.go
* `[usage]` Fixed bug with rendering command groups
* `[terminal]` Small fixes in windows stubs
> Version 3.3.1

- changelog.md
- httputil/httputil.go
- httputil/httputil_test.go
* [httputil] Added `GetRequestAddr`, `GetRemoteAddr`, `GetRemoteHost`, `GetRemotePort` methods
> Version 3.4.0

- changelog.md
- terminal/terminal.go
* `[terminal]` Improved reading user input
> Version 3.4.1

- changelog.md
- req/example_test.go
- req/req.go
- req/req_test.go
* `[req]` Global engine now in public scope and can be changed
> Version 5.0.0+

- changelog.md
- usage/usage.go
* `[usage]` Fixed examples header
> Version 5.0.1

- req/req.go
- req/req_test.go
* `[req]` Improved `SetUserAgent` method for appending subpackages versions :fire:
> Version 5.1.0

- changelog.md
- req/req.go
- req/req_test.go
- terminal/terminal_windows.go
* `[req]` Improved `Engine` initialization routine
* `[terminal]` Fixed bug in windows stub with error variable name
> Version 5.1.1

- .travis.yml
- Makefile
- changelog.md
- terminal/example_test.go
- terminal/terminal.go
- terminal/terminal_windows.go
* `[terminal]` Added password mask symbol color customization
* `[terminal]` [go-linenoise](https://github.com/essentialkaos/go-linenoise) updated to v3
> Version 5.2.0

- .travis.yml
- arg/example_test.go
- changelog.md
- log/log.go
- tmp/examples_test.go
- tmp/tmp.go
* `[log]` Code refactoring
* `[tmp]` Added permissions customization for each temp struct
> Version 5.2.1

- changelog.md
- fmtutil/example_test.go
- fmtutil/fmtutil.go
- fmtutil/fmtutil_test.go
- passwd/passwd.go
- passwd/passwd_test.go
* `[fmtutil]` Added method `ColorizePassword` for password colorization
* `[passwd]` Improved password generation and strength check
> Version 5.3.0

- changelog.md
- fmtc/fmtc.go
- fmtc/fmtc_test.go
* `[fmtc]` Fixed bug with parsing tags
> Version 5.4.1

- changelog.md
- system/user.go
* `[system]` Added method `CurrentTTY` which return path to current tty
> Version 5.5.0

- arg/arg.go
- arg/arg_test.go
- arg/example_test.go
- changelog.md
- system/info.go
- system/info_darwin.go
- system/info_linux.go
* `[system]` Added `Distribution` and `Version` info to `SystemInfo` struct
* `[arg]` Added bound arguments support
* `[arg]` Added conflicts arguments support
* `[arg]` Added method `Q` for merging several arguments to string (useful for `Alias`, `Bound` and `Conflicts`)
> Version 5.6.0

- changelog.md
- fmtutil/fmtutil.go
- fmtutil/fmtutil_test.go
- system/process/processes_linux.go
- terminal/terminal.go
- usage/example_test.go
- usage/usage.go
* `[process]` `GetTree` now can return tree for custom root process
* `[fmtutil]` Added method `CountDigits` for counting the number of digits in integer
* `[usage]` Added support for optional arguments in commands
* `[terminal]` Now `PrintWarnMessage` and `PrintErrorMessage` prints messages to stderr
* `[process]` Fixed threads marking
> Version 5.7.0

- changelog.md
- system/info_linux.go
- usage/usage.go
* `[usage]` Improved build info output
* `[system]` Improved OS version search process
> Version 5.7.1

- .travis.yml
- .travis/script.sh
- changelog.md
- netutil/netutil.go
- netutil/netutil_test.go
- usage/usage.go
* `[usage]` Showing info about latest available release on GitHub
* `[netutil]` Added method `GetIP6` which return main IPv6 address
* `[netutil]` Now GetIP return primary IPv4 address
> Version 6.2.0

- changelog.md
- usage/usage.go
* `[usage]` Improved working with GitHub API
> Version 6.2.1

- changelog.md
- fsutil/list_windows.go
* `[fsutil]` Fixed windows stubs for compatibility with latest changes
> Version 7.0.1

- .travis.yml
- changelog.md
- fsutil/file.go
- knf/knf.go
- knf/knf_test.go
- passwd/passwd.go
- passwd/passwd_test.go
- pid/pid.go
- pid/pid_test.go
- system/user.go
- system/user_darwin.go
- system/user_freebsd.go
- system/user_linux.go
- tmp/tmp.go
* `[knf]` Increased code coverage
* `[passwd]` Fixed panic in `Check` for some rare cases
* `[fsutil]` Fixed typo
* `[pid]` Fixed typo
* `[system]` Fixed typo
* `[tmp]` Fixed typo
> Version 7.0.3

- changelog.md
- system/examples_test.go
- system/info.go
- system/info_windows.go
- system/user.go
* `[system]` Added methods `CalculateNetworkSpeed` and `CalculateIOUtil` for metrics calculation without blocking main thread
* `[system]` Code and examples refactoring
> Version 7.1.0

- changelog.md
- fmtc/fmtc.go
- jsonutil/example_test.go
- jsonutil/jsonutil.go
- jsonutil/jsonutil_test.go
- sortutil/natural.go
- sortutil/sortutil_test.go
* `[sortutil]` Added methods `NatualLess` and `StringsNatual` for natural ordering
* `[jsonutil]` Added optional argument to `EncodeToFile` method with file permissions (0644 by default)
* `[jsonutil]` Code refactoring
* `[jsonutil]` Improved tests
* `[jsonutil]` Added usage examples
> Version 7.3.0

- changelog.md
- fmtutil/table/table.go
- version/example_test.go
* `[fmtutil/table]` Fixed bug with rendering data with color tags
> Version 9.1.1

- changelog.md
- terminal/terminal.go
* `[terminal]` Fixed bug with masking password in tmux
> Version 9.1.2

- changelog.md
- fmtutil/fmtutil.go
- fmtutil/fmtutil_test.go
* `[fmtutil]` Improved floating numbers formatting with `PrettyNum`
> Version 9.2.0

- changelog.md
- terminal/terminal.go
* `[terminal]` Improved title rendering for `ReadAnswer` method
* `[terminal]` Simplified API for `ReadAnswer` method
> Version 9.3.0

- changelog.md
- options/options.go
- options/options_test.go
* `[options]` Added support of mixed options (_string / bool_) 🔥
> Version 9.4.0

- changelog.md
- knf/knf.go
- knf/knf_test.go
- usage/usage.go
* `[knf]` Added new getters `GetU`, `GetU64` and `GetI64`
* `[usage]` Improved API for `NewInfo` method
> Version 9.5.0

- changelog.md
- system/procname/setprocname.go
- system/procname/setprocname_windows.go
* `[system/procname]` Added method `Replace` which replace just one argument in process command
> Version 9.6.0

- .travis/packages.list
- changelog.md
- initsystem/examples_test.go
- initsystem/initsystem.go
- readme.md
* `[initsystem]` New package for working with different init systems (sysv, upstart, systemd)
> Version 9.8.0

- changelog.md
- system/info_fs.go
* `[system]` Improved disk usage calculation (now it similar to `df` command output)
> Version 9.9.0

- changelog.md
- initsystem/initsystem_windows.go
* `[initsystem]` Added stubs for windows
> Version 9.9.2

- changelog.md
- system/info_cpu.go
- system/info_fs.go
- system/info_test.go
- system/info_windows.go
* `[system]` Added method `GetCPUStats` which return basic CPU info from `/proc/stat`
* `[system]` Improved IO utilization calculation
> Version 9.10.0

- changelog.md
- system/info_fs.go
- system/info_net.go
- system/info_test.go
* `[system]` Improved IO utilization calculation
* `[system]` Improved network speed calculation
> Version 9.11.0

- changelog.md
- system/process/process_cpu.go
* `[system/process]` Improved error handling in `GetInfo`
> Version 9.11.1

- .travis/packages.list
- changelog.md
- readme.md
- system/info_test.go
- system/process/process_cpu.go
- system/process/process_darwin.go
- system/process/process_test.go
- system/process/processes_linux.go
- usage/update/github.go
- usage/update/update_test.go
* `[system/process]` Increased code coverage (0.0% → 87.5%)
* `[usage/update]` Increased code coverage (0.0% → 80.0%)
* `[system/process]` Fixed bug with parsing CPU data
> Version 9.11.2

- changelog.md
- knf/knf_test.go
- knf/validators.go
* `[knf]` Added new validators: `NotLen`, `NotPrefix` and `NotSuffix`
* `[knf]` Validators code refactoring
> Version 9.12.0

- Makefile
- changelog.md
- system/examples_test.go
- system/info.go
- system/info_cpu.go
- system/info_fs.go
- system/info_loadavg.go
- system/info_memory.go
- system/info_net.go
- system/info_test.go
- system/info_uptime.go
- system/process/process.go
- system/process/process_cpu.go
- system/process/process_memory.go
* `[system]` Improved CPU usage calculation
* `[system/process]` Code refactoring
> Version 9.13.0

- changelog.md
- strutil/example_test.go
- strutil/strutil.go
- strutil/strutil_test.go
- system/info_fs.go
* `[strutil]` Added new method `ReadField` for reading space/tab separated fields from given data
> Version 9.14.0

- changelog.md
- initsystem/initsystem.go
* `[initsystem]` Fixed bug in SysV service state determination
> Version 9.14.1

- changelog.md
- system/info_windows.go
- system/user.go
* `[system]` Fixed windows stubs
* `[system]` Fixed bug with unclosed file descriptor
> Version 9.14.2

- changelog.md
- initsystem/initsystem.go
* `[initsystem]` Fixed bug with checking service state in systemd
> Version 9.14.3

- changelog.md
- system/info.go
- system/info_cpu.go
- system/info_fs.go
- system/info_loadavg.go
- system/info_memory.go
- system/info_net.go
- system/info_windows.go
> Version 9.14.4

- .travis.yml
- changelog.md
- readme.md
- terminal/terminal.go
* `[terminal]` Fixed bug with empty title output
> Version 9.14.5

- changelog.md
- fmtutil/table/table.go
- strutil/strutil.go
- strutil/strutil_test.go
* `[fmtutil/table]` Added method `RenderHeaders` for forced headers rendering
* `[strutil]` Improved `Fields` parsing
> Version 9.16.0

- changelog.md
- initsystem/examples_test.go
- initsystem/initsystem.go
- initsystem/initsystem_windows.go
- netutil/netutil.go
- strutil/strutil.go
- strutil/strutil_test.go
- system/procname/setprocname.go
* `[initsystem]` Added method `IsEnabled` which return info about service autostart
* `[strutil]` Added method `Copy` for forced copying of strings
* `[netutil]` Ignore TUN/TAP interfaces while searching main IP address
* `[initsystem]` Method `GetServiceState` renamed to `IsServiceWorks`
> Version 9.17.0

- changelog.md
- strutil/example_test.go
- system/procname/examples_test.go
* `[strutil]` Added usage example for `Copy` method
* `[system/procname]` Added usage examples
> Version 9.17.1

- changelog.md
- netutil/netutil.go
* `[netutil]` Improved main IP search
> Version 9.17.2

- changelog.md
- netutil/netutil.go
- netutil/netutil_test.go
- readme.md
* `[netutil]` Code refactoring
* `[netutil]` Increased code coverage (78.8% → 87.9%)
* `[options]` Fixed bug with using `Bound` or `Conflict` fields for options (thx to @gongled)
> Version 9.17.3

- changelog.md
- fmtc/fmtc.go
- fmtc/fmtc_test.go
- fmtutil/table/table.go
- options/options.go
* `[fmtc]` Added methods `Print` and `Sprintln` for better compatibility with `fmt` package
* `[options]` Code refactoring
* `[fmtutil/table]` Fixed minor bug with output formatting
> Version 9.20.0

- changelog.md
- fsutil/fs_test.go
- fsutil/helpers.go
* `[fsutil]` Improved `CopyDir` method
> Version 9.22.1

- changelog.md
- system/process/process_windows.go
* `[system/process]` Fixed windows stubs
> Version 9.22.2

- changelog.md
- options/options.go
- options/options_test.go
- usage/usage.go
* `[options]` Guess option type by default value type
* `[options]` Added check for unsupported default value type
* `[usage]` Fixed bug with aligning option info with Unicode symbols
> Version 9.22.3

- changelog.md
- log/log.go
- log/log_test.go
- log/std.go
* `[log]` Added wrapper for compatibility with stdlib logger
* `[log]` Fixed race condition issue
> Version 9.23.0

- CHANGELOG.md
- req/req.go
- req/req_test.go
* `[req]` Added method `String` for `Query` struct for query encoding
> Version 9.24.0

- CHANGELOG.md
- req/req.go
* `[req]` Added constants with status codes
> Version 9.25.0

- CHANGELOG.md
- fmtutil/fmtutil.go
* `[fmtutil]` Fixed various bugs with processing NaN values ([swptop/11](https://github.com/essentialkaos/swptop/issues/11))
> Version 9.25.1

- CHANGELOG.md
- fmtutil/fmtutil.go
- fmtutil/fmtutil_test.go
* `[fmtutil]` Improved size parser
> Version 9.25.2

- CHANGELOG.md
- sliceutil/sliceutil.go
- sliceutil/sliceutil_test.go
* `[sliceutil]` Added method `Index` which return index of give item in slice
> Version 9.26.0

- CHANGELOG.md
- README.md
- fmtutil/table/table.go
- fmtutil/table/table_test.go
* `[fmtutil/table]` Fixed bug with rendering data using not-configured table
> Version 9.26.1

- CHANGELOG.md
- easing/bounce.go
- fmtutil/fmtutil.go
- knf/validators.go
- log/log.go
- log/log_test.go
- options/options.go
- pid/pid.go
- req/req.go
- sliceutil/sliceutil.go
- strutil/example_test.go
- strutil/strutil.go
- strutil/strutil_test.go
- system/exec/exec.go
- system/user.go
- terminal/terminal.go
- timeutil/timeutil.go
- uuid/uuid.go
* `[strutil]` Optimization and improvements for `ReadField` method
* `[easing]` Code refactoring
* `[fmtutil]` Code refactoring
* `[knf]` Code refactoring
* `[log]` Code refactoring
* `[options]` Code refactoring
* `[pid]` Code refactoring
* `[req]` Code refactoring
* `[sliceutil]` Code refactoring
* `[strutil]` Code refactoring
* `[terminal]` Code refactoring
* `[timeutil]` Code refactoring
* `[uuid]` Code refactoring
> Version 9.26.3

- CHANGELOG.md
- initsystem/initsystem.go
- system/info.go
* `[initsystem]` Improved application state checking in systemd
* `[system]` Fixed typo in json tag for `CPUInfo.Average`
> Version 9.28.1

- fmtc/fmtc.go
* `[fmtc]` Added new methods `LPrintf`, `LPrintln`, `TLPrintf` and `TLPrintln`
* `[fmtc]` Code refactoring
* `[fmtc]` Fixed bug with parsing reset and modification tags (_found by go-fuzz_)
> Version 10.5.0 [+fix]

- .travis.yml
- CHANGELOG.md
- knf/knf.go
- knf/knf_test.go
- knf/validators.go
* `[knf]` Added new validators for property type validation
* `[knf]` Added `no` as a valid boolean value for `GetB`
* `[knf]` Code refactoring
> Version 10.18.0

- CHANGELOG.md
- README.md
- initsystem/initsystem_windows.go
* `[initsystem]` Fixed stubs for Windows
> Version 11.3.1

- .travis/script.sh
- CHANGELOG.md
- Makefile
- fsutil/fs.go
- fsutil/fs_test.go
- fsutil/fs_user.go
- fsutil/fs_user_unit.go
- system/user.go
* `[fsutil]` Added method `ValidatePerms` for permissions validation
* `[system]` Improved current user info caching mechanic
* `[fsutil]` Increased code coverage (98.0% → 98.8%)
> Version 11.4.0

- .scripts/packages.list
- CHANGELOG.md
- README.md
- fmtc/lscolors/examples_test.go
- fmtc/lscolors/lscolors.go
- fmtc/lscolors/lscolors_test.go
* `[fmtc/lscolors]` Added new package for colorizing file names with colors from [dircolors](https://linux.die.net/man/1/dircolors)
> Version 12.14.0

- .scripts/packages.list
- CHANGELOG.md
- README.md
- spinner/examples_test.go
- spinner/spinner.go
- spinner/spinner_test.go
- timeutil/example_test.go
- timeutil/timeutil.go
- timeutil/timeutil_test.go
* `[spinner]` Added new package for showing spinner animation for long-running tasks
* `[timeutil]` Added high precision mode for `ShortDuration`
> Version 12.15.0

- CHANGELOG.md
- system/process/examples_test.go
- system/process/process_nice.go
- system/process/process_test.go
* `[system/process]` Added methods for setting and getting CPU scheduler priority
* `[system/process]` Added methods for setting and getting IO scheduler priority
> Version 12.20.0

- CHANGELOG.md
- fmtc/fmtc.go
* `[fmtc]` [`NO_COLOR`](https://no-color.org) support
* `[fmtc]` Code refactoring
> Version 12.28.0

- CHANGELOG.md
- support/pkgs/pkgs_darwin.go
- `[support/pkgs]` Added compatibility with macOS
> Version 12.113.1

- .github/workflows/ci.yml
- .scripts/windows.ps1
- CHANGELOG.md
- req/req.go
- req/req_test.go
- timeutil/example_test.go
- timeutil/timeutil_unix.go
- timeutil/timeutil_unix_test.go
- timeutil/timeutil_windows.go
- timeutil/timeutil_windows_test.go
- **`[timeutil]`** Added method `LocalTimezone`
- **`[req]`** Added helper `Response.Save`
> Version 13.21.1

- .scripts/packages.list
- CHANGELOG.md
- README.md
- req/req.go
- req/req_test.go
- reutil/example_test.go
- reutil/reutil.go
- reutil/reutil_test.go
- uuid/prefixed/example_test.go
- uuid/prefixed/prefixed.go
- uuid/prefixed/prefixed_test.go
- **`[uuid/prefixed]`** Added package for encoding and decoding prefixed UUID's
- **`[reutil]`** Added package with helpers for working with regular expressions
- **`[req]`** Fixed bug with canceling context of request with timeout too early
> Version 13.22.0
